services:
  gemeente_amsterdam_brievenhulp.repositories.hulpverlener:
    class: GemeenteAmsterdam\BrievenhulpBundle\Entity\HulpverlenerRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - GemeenteAmsterdam\BrievenhulpBundle\Entity\Hulpverlener
  gemeente_amsterdam_brievenhulp.repositories.hulpvraag:
    class: GemeenteAmsterdam\BrievenhulpBundle\Entity\HulpvraagRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - GemeenteAmsterdam\BrievenhulpBundle\Entity\Hulpvraag
  gemeente_amsterdam_brievenhulp.repositories.tag:
    class: GemeenteAmsterdam\BrievenhulpBundle\Entity\TagRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - GemeenteAmsterdam\BrievenhulpBundle\Entity\Tag
  gemeente_amsterdam_brievenhulp.repositories.afzender:
    class: GemeenteAmsterdam\BrievenhulpBundle\Entity\AfzenderRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - GemeenteAmsterdam\BrievenhulpBundle\Entity\Afzender
  gemeente_amsterdam_brievenhulp.repositories.auditlogentry:
    class: GemeenteAmsterdam\BrievenhulpBundle\Entity\AuditLogEntryRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - GemeenteAmsterdam\BrievenhulpBundle\Entity\AuditLogEntry
      
  gemeente_amsterdam_brievenhulp.listeners.security:
    class: GemeenteAmsterdam\BrievenhulpBundle\Listener\SecurityListener
    arguments:
      - '@doctrine'
      - '@request_stack'
      - '@gemeente_amsterdam_brievenhulp.repositories.hulpverlener'
    tags:
      - { name: 'kernel.event_listener', event: 'security.interactive_login' }
      - { name: 'kernel.event_listener', event: 'security.authentication.failure', method: onAuthenticationFailure }
      