security:

    encoders:
        GemeenteAmsterdam\BrievenhulpBundle\Entity\Hulpverlener:
            algorithm: bcrypt

    providers:
        hulpverleners:
            entity:
                class: GemeenteAmsterdamBrievenhulpBundle:Hulpverlener
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        hulpverlener:
            pattern: ^/hulpverlener
            anonymous: ~
            form_login:
                login_path: gemeenteamsterdam_brievenhulp_hulpverlener_login
                check_path: gemeenteamsterdam_brievenhulp_hulpverlener_login
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /hulpverlener
            logout:
                path: /hulpverlener/logout
                target: /hulpverlener
        main:
            anonymous: ~
    
    access_control:
        - { path: ^/hulpverlener/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/hulpverlener/hulpvraag/(.*)/(.*)/ontvanger/(.*)/(.*), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/hulpverlener, roles: [ROLE_USER, ROLE_ADMIN] }
