parameters:
    database_host: '%brievenhulp.database_host%'
    database_port: '%brievenhulp.database_port%'
    database_name: '%brievenhulp.database_name%'
    database_user: '%brievenhulp.database_user%'
    database_password: '%brievenhulp.database_password%'
    mailer_transport: '%brievenhulp.mailer_transport%'
    mailer_host: '%brievenhulp.mailer_host%'
    mailer_user: '%brievenhulp.mailer_user%'
    mailer_password: '%brievenhulp.mailer_password%'
    mailer_port: '%brievenhulp.mailer_port%'
    mailer_encryption: '%brievenhulp.mailer_encryption%'
    secret: '%brievenhulp.secret%'
    mail_from: '%brievenhulp.mail_from%'
    mail_cc: '%brievenhulp.mail_cc%'
    auto_login_from_email: '%brievenhulp.auto_login_from_email%'
    retention_policy: '%brievenhulp.retention_policy%'
    router.request_context.host: '%brievenhulp.request_context_host%'
    router.request_context.scheme: '%brievenhulp.request_context_scheme%'
    router.request_context.base_url: '%brievenhulp.request_context_base_url%'
    messagebird_enable: '%brievenhulp.messagebird_enable%'
    messagebird_api_key: '%brievenhulp.messagebird_api_key%'
    messagebird_sms_originator: '%brievenhulp.sms_orginator%'
    piwik_site_id: '%brievenhulp.piwik_site_id%'
    trusted_proxies: '%brievenhulp.trusted_proxies%'
